from django.urls import path
from . import views

urlpatterns = [
    path("query_places", views.fetch_places, name="index"),
    path("fetch_and_scrape", views.fetch_and_scrape, name="index"),
    path("filter_email", views.filter_email, name="index"),
    path("leads", views.list_leads, name='list leads'),
    path("leads/create", views.create_lead, name="create lead"),
    path("leads/<str:place_id>", views.delete_lead, name="delete lead"),
    path("retry_scrape", views.retry_scrape, name='retry scrape'),
    path("leads_count", views.leads_count, name='count of leads'),
    path("filter_email", views.filter_email, name="index"),
    path("tasks", views.list_tasks, name="List Tasks"),
    path("call_lead", views.call_lead, name="Call Lead"),
    path("email_lead", views.send_email_to_lead, name="Email Lead"),
    path("emailed_leads",views.get_emailed_leads,name="Get all emailed leads"),
    path("called_leads",views.get_called_leads, name="Called Leads"),
    path("lead_call_conversations",views.get_lead_call_conversations, name="Called Leads"),
    path("lead_call_conversation_audio",views.get_lead_call_conversation_audio, name="Called Leads"),
    path("email_history", views.get_email_history, name="get conversation history"),
    path("send_email_message_to_lead", views.send_email, name="sends a message to lead"),
    path("generate_ai_reply", views.generate_ai_reply, name="generate AI reply suggestions"),
    path("stats", views.get_stats, name="dashboard stats"),
    path("notifications", views.get_notifications, name="get notifications"),
    path("notifications/mark_read", views.mark_notifications_read, name="mark notifications read"),
    path("notifications/mark_all_read", views.mark_all_notifications_read, name="mark all notifications read"),
    path("tasks/purge_stale", views.purge_stale_schedules, name="purge stale schedules"),
    path("email_conversation", views.delete_email_conversation, name="delete email conversation"),
]
