# Generated by Django 5.2.1 on 2025-09-10 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('description', models.TextField(blank=True)),
                ('business_type', models.CharField(blank=True, default='', max_length=128)),
                ('website', models.URLField(blank=True, default='', null=True)),
                ('formatted_address', models.TextField(blank=True, default='', null=True)),
                ('weekly_opening_hours', models.TextField(blank=True, default='', null=True)),
                ('national_phone_number', models.CharField(blank=True, default='', max_length=128)),
                ('international_phone_number', models.CharField(blank=True, default='', max_length=128)),
                ('scrape_error', models.CharField(blank=True, default=None, max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('business_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amaya_api.lead')),
            ],
        ),
    ]
