# Generated by Django 5.2.6 on 2025-09-13 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amaya_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='business_type',
        ),
        migrations.AddField(
            model_name='lead',
            name='business_types',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AddField(
            model_name='lead',
            name='place_id',
            field=models.CharField(default='', max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
