# Generated by Django 5.2.6 on 2025-09-13 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amaya_api', '0002_remove_lead_business_type_lead_business_types_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='business_id',
        ),
        migrations.AddField(
            model_name='email',
            name='business',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='amaya_api.lead'),
            preserve_default=False,
        ),
    ]
