# Generated by Django 5.2.6 on 2025-09-13 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amaya_api', '0003_remove_email_business_id_email_business'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='name',
            field=models.CharField(max_length=128),
        ),
    ]
