# Generated by Django 5.2.6 on 2025-09-24 06:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amaya_api', '0004_alter_lead_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 9, 24, 6, 8, 53, 885038, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lead',
            name='updated_now',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
