# Generated by Django 5.2.6 on 2025-10-28 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amaya_api', '0005_lead_created_at_lead_updated_now'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='international_phone_number',
            field=models.CharField(blank=True, default='', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='national_phone_number',
            field=models.CharField(blank=True, default='', max_length=128, null=True),
        ),
    ]
