# Generated by Django 5.2.6 on 2025-11-01 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amaya_api', '0006_alter_lead_international_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='business_types',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='lead',
            name='name',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='lead',
            name='place_id',
            field=models.CharField(default='', max_length=512, unique=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='scrape_error',
            field=models.CharField(blank=True, default=None, max_length=512),
        ),
        migrations.AlterField(
            model_name='lead',
            name='website',
            field=models.URLField(blank=True, default='', max_length=1024, null=True),
        ),
    ]
