# Generated by Django 5.2.6 on 2025-11-19 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("amaya_api", "0007_alter_lead_business_types_alter_lead_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CallStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sucess", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("initiated", "Initiated"),
                            ("in-progress", "inprogress"),
                            ("processing", "Processing"),
                            ("Done", "done"),
                            ("failed", "Failed"),
                        ],
                        default="initiated",
                        max_length=64,
                    ),
                ),
                ("conversation_id", models.CharField(default="", max_length=128)),
                ("call_sid", models.CharField(default="", max_length=128)),
            ],
        ),
    ]
