# Generated by Django 5.2.6 on 2025-11-19 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("amaya_api", "0008_callstatus"),
    ]

    operations = [
        migrations.RenameField(
            model_name="callstatus",
            old_name="sucess",
            new_name="success",
        ),
        migrations.AlterField(
            model_name="callstatus",
            name="status",
            field=models.CharField(
                choices=[
                    ("initiated", "Initiated"),
                    ("in-progress", "In Progress"),
                    ("processing", "Processing"),
                    ("done", "Done"),
                    ("failed", "Failed"),
                ],
                default="initiated",
                max_length=64,
            ),
        ),
    ]
