# Generated by Django 5.2.6 on 2025-11-28 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("amaya_api", "0009_rename_sucess_callstatus_success_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="call_sent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="lead",
            name="email_sent",
            field=models.BooleanField(default=False),
        ),
    ]
