# Generated by Django 5.2.6 on 2025-12-23 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("amaya_api", "0010_lead_call_sent_lead_email_sent"),
    ]

    operations = [
        migrations.CreateModel(
            name="CallConversations",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("success", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("initiated", "Initiated"),
                            ("in-progress", "In Progress"),
                            ("processing", "Processing"),
                            ("done", "Done"),
                            ("failed", "Failed"),
                        ],
                        default="initiated",
                        max_length=64,
                    ),
                ),
                ("conversation_id", models.CharField(default="", max_length=128)),
                ("call_sid", models.CharField(default="", max_length=128)),
                ("created_at", models.DateField(auto_now_add=True)),
                (
                    "lead",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="call_conversations",
                        to="amaya_api.lead",
                    ),
                ),
            ],
        ),
    ]
