# Generated by Django 5.2.6 on 2026-06-11 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amaya_api', '0012_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='scrape_error',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
    ]
