# Generated by Django 5.2.6 on 2026-06-13 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amaya_api', '0013_alter_lead_scrape_error'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('cold_reach', 'Cold Reach'), ('follow_up', 'Follow-up'), ('re_engage', 'Re-engagement'), ('thank_you', 'Thank You'), ('general', 'General')], default='general', max_length=64)),
                ('subject', models.CharField(blank=True, default='', max_length=512)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
    ]
