# Generated by Django 5.2.6 on 2026-06-14 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amaya_api', '0015_seed_email_templates'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplate',
            name='images',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
